/**
 * Mock data for Two-Factor Authentication (2FA)
 * These values are for development and testing purposes only.
 * DO NOT use these values in production environments.
 */

export const MOCK_2FA = {
  /**
   * Example secret key for development
   * This is a static key used only for testing and development
   */
  SECRET_KEY: 'JBSWY3DPEHPK3PXP',
  
  /**
   * Example OTP Auth URL with the test secret
   * Format: otpauth://totp/{issuer}:{account}?secret={secret}&issuer={issuer}
   */
  EXAMPLE_AUTH_URL: 'otpauth://totp/Example:user@example.com?secret=JBSWY3DPEHPK3PXP&issuer=Example',
  
  /**
   * Example verification code (for testing only)
   * In a real scenario, this would be generated by an authenticator app
   */
  EXAMPLE_CODE: '123456'
} as const;

// Type for the mock data to ensure type safety
export type Mock2FAData = typeof MOCK_2FA; 